import {Nutrient} from '../model/nutrient';

export const NUTRIENTS: Nutrient[] = [
  { id: 1, code:'100', name: 'Dry Matter' },
  { id: 2, code:'101', name: 'Crude Protein' },
  { id: 3, code:'102', name: 'Fat' },
  { id: 4, code:'100', name: 'Dry Matter' },
  { id: 5, code:'101', name: 'Crude Protein' },
  { id: 6, code:'102', name: 'Fat' },
  { id: 7, code:'100', name: 'Dry Matter' },
  { id: 8, code:'101', name: 'Crude Protein' },
  { id: 9, code:'102', name: 'Fat' },
  { id: 10, code:'100', name: 'Dry Matter' },
  { id: 11, code:'101', name: 'Crude Protein' },
  { id: 12, code:'102', name: 'Fat' },
  { id: 13, code:'100', name: 'Dry Matter' },
  { id: 14, code:'101', name: 'Crude Protein' },
  { id: 15, code:'102', name: 'Fat' },
  { id: 16, code:'100', name: 'Dry Matter' },
  { id: 17, code:'101', name: 'Crude Protein' },
  { id: 18, code:'102', name: 'Fat' },
  { id: 19, code:'100', name: 'Dry Matter' },
  { id: 20, code:'101', name: 'Crude Protein' },
  { id: 21, code:'102', name: 'Fat' },
];
